# Generated by Django 5.1.3 on 2024-11-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
                ('decano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('snies', models.CharField(max_length=20)),
                ('registro_calificado', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=20)),
                ('ciclo', models.CharField(max_length=20)),
                ('plan_estudios', models.JSONField()),
                ('caracteristicas', models.JSONField()),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.persona')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta_academica.facultad')),
            ],
        ),
    ]
