# Generated by Django 5.1.3 on 2024-11-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oferta_academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('interesado', 'Interesado'), ('registrado', 'Registrado'), ('aspirante', 'Aspirante'), ('matriculado', 'Matriculado'), ('estudiante', 'Estudiante EAM')], max_length=20)),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oferta_academica.programaacademico')),
                ('referido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='estudiantes.estudiante')),
            ],
        ),
    ]
