# Generated by Django 5.1.3 on 2024-11-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('estudiantes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.asesor'),
        ),
        migrations.AddField(
            model_name='lead',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='step',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='lead',
            name='step_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.step'),
        ),
    ]
